name: Upload to modio

on:
  push:
    tags:
      - '*.*.*'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package
        id: package
        run: |
          name="notebook"
          version="$(grep -o '<version>.*</version>' mod.xml | sed -e 's|<version>\([^<]*\)</version>|\1|g')"
          filename="$name_$version.zip"
          zip "$filename" *

          echo "::set-output name=modfile::$filename"
          echo "::set-output name=version::$version"

      - name: Upload
        uses: nickelc/upload-to-modio@v1
        with:
          token: ${{ secrets.MODIO_TOKEN }}
          game: 34
          mod: 67662
          version: ${{ steps.package.outputs.version }}
          path: ${{ steps.package.outputs.modfile }}
